"""add DocumentVersion

Revision ID: 44a0cb447101
Revises: 62c85955fa1b
Create Date: 2025-10-16 15:20:22.052244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '44a0cb447101'
down_revision = '62c85955fa1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
